tracker_type: strongsort
reid_weights: outputs/reid/checkpoints/best_reid.pt
max_iou_distance: 0.7
max_age: 30
n_init: 3
nn_budget: 100
mc_lambda: 0.995
ema_alpha: 0.8
max_time_lost: 30
max_track_history: 50
track_high_thresh: 0.5
track_low_thresh: 0.05
new_track_thresh: 0.6
track_buffer: 30
match_thresh: 0.8
iou_threshold: 0.3
max_n_tracks: 256
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: True
half: False
save_txt: False
save_vid: False
device: auto