# Phase 2 YOLO params (fine-tune phase 1 best weights for 'other' class only)
model: "models/football_detector_phase1/weights/best.pt"
imgsz: 960
batch: 24
rect: false
multi_scale: false
resume: false
epochs: 90
pretrained: true
optimizer: "AdamW"
deterministic: false
lr0: 0.0005
lrf: 0.01
nbs: 64
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 4
warmup_momentum: 0.8
warmup_bias_lr: 0.1
cos_lr: true
box: 7.5
cls: 0.5
dfl: 2.0
hsv_h: 0.005
hsv_s: 0.2
hsv_v: 0.2
degrees: 0.5
translate: 0.05
scale: 0.25
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.05
mixup: 0.0
copy_paste: 0.0
erasing: 0.0
val: true
augment: false
auto_augment: false
conf: 0.12
iou: 0.6
max_det: 200
workers: 8
cache: false
patience: 25
save_period: 5
profile: false
fraction: 1.0
project_name: "football_detector_phase2"
exist_ok: true
save: true

freeze:
	- 0
